In [7]:
import numpy as np

In [18]:
def stoneGame(p):
    n = len(p)
    dp = [[0] * n for i in range(n)]
    for i in range(n): dp[i][i] = p[i]
    for d in range(1, n):
        for i in range(n - d):
            dp[i][i + d] = max(p[i] - dp[i + 1][i + d], p[i + d] - dp[i][i + d - 1])
            print(p[i], dp[i + 1][i + d], p[i + d], dp[i][i + d - 1])
            print(p[i] - dp[i + 1][i + d], p[i + d] - dp[i][i + d - 1])
            print(d, i)
            print(np.array(dp))
            print()
    return dp[0][-1] > 0

In [19]:
stoneGame([5,3,4,5])

5 3 3 5
2 -2
1 0
[[5 2 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]

3 4 4 3
-1 1
1 1
[[5 2 0 0]
 [0 3 1 0]
 [0 0 4 0]
 [0 0 0 5]]

4 5 5 4
-1 1
1 2
[[5 2 0 0]
 [0 3 1 0]
 [0 0 4 1]
 [0 0 0 5]]

5 1 4 2
4 2
2 0
[[5 2 4 0]
 [0 3 1 0]
 [0 0 4 1]
 [0 0 0 5]]

3 1 5 1
2 4
2 1
[[5 2 4 0]
 [0 3 1 4]
 [0 0 4 1]
 [0 0 0 5]]

5 4 5 4
1 1
3 0
[[5 2 4 1]
 [0 3 1 4]
 [0 0 4 1]
 [0 0 0 5]]



True